### ISSUE TITLE
Uncaught TypeError: shell.openItem is not a function

### ISSUE THREAD

**Issue by AERodgers** [aterenin/right-click-external-app#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.56.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Education
**Thrown From**: [right-click-external-app](https://github.com/aterenin/right-click-external-app) package 1.0.0

### Stack Trace

Uncaught TypeError: shell.openItem is not a function

```
At C:\Users\antoi\.atom\packages\right-click-external-app\lib\right-click-external-app.coffee:13

TypeError: shell.openItem is not a function
    at Object.openFile (/packages/right-click-external-app/lib/right-click-external-app.coffee:13:11)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:351740)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:350215)
    at AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:1:833422)
    at EventEmitter.t (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:1:841476)
    at EventEmitter.emit (events.js:223:5)
    at Object.onMessage (electron/js2c/renderer_init.js:115:818)
```

### Commands

```
     -0:58.8.0 core:move-to-bottom (input.hidden-input)
     -0:12.5.0 core:move-to-top (input.hidden-input)
     -0:07.3.0 right-click-external-app:open (span.name.icon.icon-file-text)
```

### Non-Core Packages

```
atom-format-lua 0.1.5 
kite 0.204.0 
language-lua-wow 0.2.0 
language-praat 1.5.0 
right-click-external-app 1.0.0 
```

**Comment by aterenin** [comment]
Looks like the API has changed since the time I wrote this package, and the function `shell.openItem` no longer exists. This is likely renamed to something else. I'm no longer using Atom, so not familiar with the API.

If someone wants to look up what the new API is, it should be an easy fix. I'd welcome a PR.

**Comment by MoeweX** [comment]
more information on the API change: https://github.com/electron/governance/blob/master/wg-api/spec-documents/shell-openitem.md

**Comment by aterenin** [comment]
Looks like only a few lines fix - change `openItem` to `openPath` and handle the promise appropriately. Happy to take a PR if someone wants to spend a few minutes to test that and make sure it works.

**Comment by wongjiahau** [comment]
Why was it renamed from `openItem` to `openPath`?
